/**
 * 前端兜底默认配置。
 *
 * 定位：仅用于 `api/config` 尚未返回（或请求失败）时的表单初值，
 *       因此这里必须与后端 `ConfigUtil` 的默认值保持一致，且**不得**包含任何
 *       与开发机绑定的绝对路径（历史问题：曾硬编码作者本机 macOS 路径，
 *       Linux/Docker 用户一旦在接口失败时保存就会写到不存在的目录）。
 *
 * 下载路径模板留空：真实默认值由后端按平台推导（macOS/Windows 用 ~/Movies，
 * 其余用根路径下的 movies），接口正常返回时会被覆盖。
 */
export let configData = {
    "mikanHost": "https://mikanani.me",
    "tmdbApi": "https://api.themoviedb.org",
    "tmdbApiKey": "",
    "tmdbImage": "https://image.tmdb.org",
    "tmdbAnime": true,
    "downloadToolType": "qBittorrent",
    "downloadRetry": 3,
    "downloadToolHost": "",
    "downloadToolUsername": "",
    "downloadToolPassword": "",
    "qbUseDownloadPath": false,
    "qbContentLayout": "Original",
    "ratioLimit": -2,
    "seedingTimeLimit": -2,
    "inactiveSeedingTimeLimit": -2,
    "downloadPathTemplate": "",
    "ovaDownloadPathTemplate": "",
    "completedPathTemplate": "",
    "customTags": [],
    "delayedDownload": 0,
    "newTorrentWaitHours": 2,
    "rssSleepMinutes": 15,
    "renameSleepSeconds": 10,
    "rename": true,
    "rss": true,
    "rssTimeout": 20,
    "rssRetry": 3,
    "fileExist": false,
    "awaitStalledUP": true,
    "delete": false,
    "deleteStandbyRSSOnly": false,
    "offset": false,
    // 后端默认 true（见 ConfigUtil.setTitleYear(true)）
    "titleYear": true,    "autoDisabled": false,
    "skip5": true,
    "standbyRss": false,
    "coexist": false,
    "copyMasterToStandby": false,
    // 后端上限 512，默认 128
    "logsMax": 128,
    "debug": false,
    "proxy": false,
    "proxyList": "",
    "proxyHost": "",
    "proxyPort": 8080,
    "proxyUsername": "",
    "proxyPassword": "",
    "downloadCount": 0,
    "login": {
        "username": "admin",
        "password": ""
    },
    "multiLoginForbidden": true,
    "loginEffectiveHours": 3,
    "exclude": [
        "720[Pp]",
        "\\d-\\d",
        "合集",
        "特别篇"
    ],
    "importExclude": false,
    "enabledExclude": false,
    "bgmJpName": false,
    // 后端默认 true
    "tmdb": true,
    "tmdbId": false,
    "tmdbIdPlexMode": false,
    "tmdbLanguage": "zh-CN",
    "tmdbRomaji": false,
    "tmdbOriginalName": false,
    "ipWhitelist": false,
    "ipWhitelistStr": "",
    "omit": true,
    "bgmToken": "",
    "bgmTokenType": "INPUT",
    "bgmAppID": "",
    "bgmAppSecret": "",
    "bgmRedirectUri": "",
    "bgmApi": "https://api.bgm.tv",
    "apiKey": "",
    "downloadNew": false,
    "innerIP": false,
    "renameTemplate": "[${subgroup}] ${title} S${seasonFormat}.E${episodeFormat} ${episodeTitle}",
    "ovaRenameTemplate": "${title} (${year}) [${subgroup}]",
    "renameDelYear": false,
    "renameDelTmdbId": false,
    "maxFileNameLength": 0,
    // 后端默认 true
    "verifyLoginIp": true,
    "autoTrackersUpdate": false,
    "trackersUpdateUrls": "https://cf.trackerslist.com/best.txt",
    "notificationTemplate": "",
    "autoUpdate": false,
    // 后端字段：禁止自动更新（导入/导出时保持一致）
    "disableUpdate": true,
    "version": "",
    "bgmImageSize": "medium",
    "customCss": "",
    "customJs": "",
    "customEpisode": false,
    "customEpisodeStr": "",
    "customEpisodeGroupIndex": 2,
    "provider": "115 Open",
    "upload": true,
    "upLimit": 0,
    "dlLimit": 0,
    "expirationTime": 0,
    "outTradeNo": "",
    "verifyExpirationTime": false,
    "tryOut": false,
    "procrastinating": false,
    "procrastinatingDay": 14,
    "procrastinatingMasterOnly": true,
    "githubToken": "",
    "updateTotalEpisodeNumber": false,
    "forceUpdateTotalEpisodeNumber": false,
    "alistDownloadTimeout": 60,
    "alistCloudDownloadDir": "",
    "alistDownloadRetryNumber": 5,
    "alistRefresh": false,
    "alistRefreshDelayed": 0,
    "configBackup": false,
    "configBackupDay": 7,
    "completed": false,
    "notificationConfigList": [],
    "priorityKeywordsEnable": false,
    "priorityKeywords": [],
    "limitLoginAttempts": true,
    "buildInfo": '',
    "reverseProxyTrustIpList": ["127.0.0.1"],
    "reverseProxyTrustIpListEnabled": false,
    "subtitleIndependentFolderEnabled": false,
    "subtitleIndependentFolderName": "Subs",
    "allowCors": false,
    "corsOrigins": "",
    "networkPrefer": "",
    "autoStart": false,
    "scrape": false,
    "followDay": 14,
    "bangumiIniEnabled": false,
    "replace": false,
    "sortType": "SCORE"
}
